version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    environment:
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
