name: Build and Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Clear Docker Cache
      run: docker builder prune -af

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Network
      run: docker network create app-network

    - name: Build Backend
      run: docker build ./backend -t backend:latest

    - name: Build Frontend
      run: docker build ./frontend -t frontend:latest

    - name: Run Backend Tests
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        docker run --rm --network app-network -e MONGO_URI=${{ secrets.MONGO_URI }} backend:latest sh -c "npm test"

    - name: Run Frontend Tests
      run: |
        docker run --rm --network app-network frontend:latest sh -c "npm test"

    - name: Cleanup
      if: always()
      run: docker network rm app-network
