name: Build and Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Clear Docker Cache
      run: docker builder prune -af

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Network
      run: docker network create app-network

    - name: Build and Run Backend
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        docker build ./backend -t backend:latest
        docker run -d --name backend --network app-network -e MONGO_URI=${MONGO_URI} backend:latest

    - name: Build and Run Frontend
      run: |
        docker build ./frontend -t frontend:latest
        docker run -d --name frontend --network app-network frontend:latest

    - name: Run Backend Tests
      run: docker run --rm --network app-network -e MONGO_URI=${{ secrets.MONGO_URI }} backend:latest npm test

    - name: Run Frontend Tests
      run: docker run --rm --network app-network frontend:latest npm test

    - name: Cleanup
      if: always()
      run: |
        docker stop backend frontend
        docker rm backend frontend
        docker network rm app-network
