name: Build and Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-run:
    runs-on: ubuntu-latest

    steps:
    
    - name: Clear Docker Cache
      run: docker builder prune -af

      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Network
      run: docker network create app-network

    - name: Build and Run Backend
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        docker build ./backend -t backend:18
        docker run -d --name backend --network app-network -e MONGO_URI=${MONGO_URI} -p 5000:5000 backend:latest
        docker ps

    - name: Build and Run Frontend
      run: |
        docker build ./frontend -t frontend:18
        docker run -d --name frontend --network app-network -p 3001:3000 frontend:latest
        docker ps


    - name: Additional commands
      run: |
        echo "Run tests or other commands here"
        # Example: curl -f http://localhost:3001

    - name: Cleanup
      if: always()
      run: |
        docker stop backend frontend
        docker rm backend frontend
        docker network rm app-network